Sidekiq.configure_client do |config|
  config.redis = { size: 1, url: ENV['REDIS_URL'], namespace: FestiSwap }
end

Sidekiq.configure_server do |config|
  config.redis = { size: 3, url: ENV['REDIS_URL'], namespace: FestiSwap }
end